//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4016
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamlSerializerTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YamlSerializerTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   - Mark McGwire
        ///- Sammy Sosa
        ///- Ken Griffey
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_1 {
            get {
                return ResourceManager.GetString("Example2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---
        ///hr:
        ///  - Mark McGwire
        ///  # Following node labeled SS
        ///  - &amp;SS Sammy Sosa
        ///rbi:
        ///  - *SS # Subsequent occurrence
        ///  - Ken Griffey
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_10 {
            get {
                return ResourceManager.GetString("Example2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ? - Detroit Tigers
        ///  - Chicago cubs
        ///:
        ///  - 2001-07-23
        ///
        ///? [ New York Yankees,
        ///    Atlanta Braves ]
        ///: [ 2001-07-02, 2001-08-12,
        ///    2001-08-14 ]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_11 {
            get {
                return ResourceManager.GetString("Example2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---
        ///# Products purchased
        ///- item    : Super Hoop
        ///  quantity: 1
        ///- item    : Basketball
        ///  quantity: 4
        ///- item    : Big Shoes
        ///  quantity: 1
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_12 {
            get {
                return ResourceManager.GetString("Example2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # ASCII Art
        ///--- |
        ///  \//||\/||
        ///  // ||  ||__ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_13 {
            get {
                return ResourceManager.GetString("Example2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- &gt;
        ///  Mark McGwire&apos;s
        ///  year was crippled
        ///  by a knee injury.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_14 {
            get {
                return ResourceManager.GetString("Example2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;
        /// Sammy Sosa completed another
        /// fine season with great stats.
        ///
        ///   63 Home Runs
        ///   0.288 Batting Average
        ///
        /// What a year!
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_15 {
            get {
                return ResourceManager.GetString("Example2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sammy Sosa completed another fine season with great stats.
        ///
        ///  63 Home Runs
        ///  0.288 Batting Average
        ///
        ///What a year!
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_15Result {
            get {
                return ResourceManager.GetString("Example2_15Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name: Mark McGwire
        ///accomplishment: &gt;
        ///  Mark set a major league
        ///  home run record in 1998.
        ///stats: |
        ///  65 Home Runs
        ///  0.278 Batting Average
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_16 {
            get {
                return ResourceManager.GetString("Example2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unicode: &quot;Sosa did fine.\u263A&quot;
        ///control: &quot;\b1998\t1999\t2000\n&quot;
        ///hex esc: &quot;\x0d\x0a is \r\n&quot;
        ///
        ///single: &apos;&quot;Howdy!&quot; he cried.&apos;
        ///quoted: &apos; # Not a &apos;&apos;comment&apos;&apos;.&apos;
        ///tie-fighter: &apos;|\-*-/|&apos;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_17 {
            get {
                return ResourceManager.GetString("Example2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   plain:
        ///  This unquoted scalar
        ///  spans many lines.
        ///
        ///quoted: &quot;So does this
        ///  quoted scalar.\n&quot;
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_18 {
            get {
                return ResourceManager.GetString("Example2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hr:  65    # Home runs
        ///avg: 0.278 # Batting average
        ///rbi: 147   # Runs Batted In
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_2 {
            get {
                return ResourceManager.GetString("Example2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   american:
        ///  - Boston Red Sox
        ///  - Detroit Tigers
        ///  - New York Yankees
        ///national:
        ///  - New York Mets
        ///  - Chicago Cubs
        ///  - Atlanta Braves に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_3 {
            get {
                return ResourceManager.GetString("Example2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -
        ///  name: Mark McGwire
        ///  hr:   65
        ///  avg:  0.278
        ///-
        ///  name: Sammy Sosa
        ///  hr:   63
        ///  avg:  0.288
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_4 {
            get {
                return ResourceManager.GetString("Example2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - [name        , hr, avg  ]
        ///- [Mark McGwire, 65, 0.278]
        ///- [Sammy Sosa  , 63, 0.288]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_5 {
            get {
                return ResourceManager.GetString("Example2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mark McGwire: {hr: 65, avg: 0.278}
        ///Sammy Sosa: {
        ///    hr: 63,
        ///    avg: 0.288
        ///  }
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_6 {
            get {
                return ResourceManager.GetString("Example2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Ranking of 1998 home runs
        ///---
        ///- Mark McGwire
        ///- Sammy Sosa
        ///- Ken Griffey
        ///
        ///# Team ranking
        ///---
        ///- Chicago Cubs
        ///- St Louis Cardinals
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_7 {
            get {
                return ResourceManager.GetString("Example2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---
        ///time: 20:03:20
        ///player: Sammy Sosa
        ///action: strike (miss)
        ///...
        ///---
        ///time: 20:03:47
        ///player: Sammy Sosa
        ///action: grand slam
        ///...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_8 {
            get {
                return ResourceManager.GetString("Example2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---
        ///hr: # 1998 hr ranking
        ///  - Mark McGwire
        ///  - Sammy Sosa
        ///rbi:
        ///  # 1998 rbi ranking
        ///  - Sammy Sosa
        ///  - Ken Griffey
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example2_9 {
            get {
                return ResourceManager.GetString("Example2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   commercial-at: @text
        ///grave-accent: `text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_10 {
            get {
                return ResourceManager.GetString("Example5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |
        ///  Line break (no glyph)
        ///  Line break (glyphed)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_11 {
            get {
                return ResourceManager.GetString("Example5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Tabs and spaces
        ///quoted: &quot;Quoted 	&quot;
        ///block:	|
        ///  void main() {
        ///  	printf(&quot;Hello, world!\n&quot;);
        ///  } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_12 {
            get {
                return ResourceManager.GetString("Example5_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Fun with \\ \&quot; \a \b \e \f \n \r \t \v \0 \  \_ \N \L \P \x41 \u0041 \U00000041&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_13 {
            get {
                return ResourceManager.GetString("Example5_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sequence:
        ///- one
        ///- two
        ///mapping:
        ///  ? sky
        ///  : blue
        ///  sea : green
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_3 {
            get {
                return ResourceManager.GetString("Example5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sequence: [ one, two, ]
        ///mapping: { sky: blue, sea: green } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_4 {
            get {
                return ResourceManager.GetString("Example5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Comment only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_5 {
            get {
                return ResourceManager.GetString("Example5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   anchored: !local &amp;anchor value
        ///alias: *anchor
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_6 {
            get {
                return ResourceManager.GetString("Example5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   literal: |
        ///  some
        ///  text
        ///folded: &gt;
        ///  some
        ///  text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_7 {
            get {
                return ResourceManager.GetString("Example5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   single: &apos;text&apos;
        ///double: &quot;text&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_8 {
            get {
                return ResourceManager.GetString("Example5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %YAML 1.2
        ///--- text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example5_9 {
            get {
                return ResourceManager.GetString("Example5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///     # Leading comment line spaces are
        ///   # neither content nor indentation.
        ///    
        ///Not indented:
        /// By one space: |
        ///    By four
        ///      spaces
        /// Flow style: [    # Leading spaces
        ///   By two,        # in flow style
        ///  Also by two,    # are neither
        ///  	Still by two  # content nor
        ///    ]             # indentation.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_1 {
            get {
                return ResourceManager.GetString("Example6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///     # Comment
        ///   
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_10 {
            get {
                return ResourceManager.GetString("Example6_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   key:    # Comment
        ///        # lines
        ///  value
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_11 {
            get {
                return ResourceManager.GetString("Example6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   { first: Sammy, last: Sosa }:
        ///# Statistics:
        ///  hr:  # Home runs
        ///     65
        ///  avg: # Average
        ///   0.278
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_12 {
            get {
                return ResourceManager.GetString("Example6_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %FOO  bar baz  # Should be ignored
        ///               # with a warning.
        ///--- &quot;foo&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_13 {
            get {
                return ResourceManager.GetString("Example6_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %YAML 1.3 # Attempt parsing
        ///           # with a warning
        ///---
        ///&quot;foo&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_14 {
            get {
                return ResourceManager.GetString("Example6_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %YAML 1.2
        ///%YAML 1.1
        ///foo
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_15 {
            get {
                return ResourceManager.GetString("Example6_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !yaml! tag:yaml.org,2002:
        ///---
        ///!yaml!str &quot;foo&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_16 {
            get {
                return ResourceManager.GetString("Example6_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG ! !foo
        ///%TAG ! !foo
        ///bar
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_17 {
            get {
                return ResourceManager.GetString("Example6_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Private
        ///!foo &quot;bar&quot;
        ///...
        ///# Global
        ///%TAG ! tag:example.com,2000:app/
        ///---
        ///!foo &quot;bar&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_18 {
            get {
                return ResourceManager.GetString("Example6_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !! tag:example.com,2000:app/
        ///---
        ///!!int 1 - 3 # Interval, not integer
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_19 {
            get {
                return ResourceManager.GetString("Example6_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ? a
        ///: -	b
        ///  -  -	c
        ///     - d
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_2 {
            get {
                return ResourceManager.GetString("Example6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !e! tag:example.com,2000:app/
        ///---
        ///!e!foo &quot;bar&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_20 {
            get {
                return ResourceManager.GetString("Example6_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !m! !my-
        ///--- # Bulb here
        ///!m!light fluorescent
        ///...
        ///%TAG !m! !my-
        ///--- # Color here
        ///!m!light green
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_21 {
            get {
                return ResourceManager.GetString("Example6_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !e! tag:example.com,2000:app/
        ///---
        ///- !e!foo &quot;bar&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_22 {
            get {
                return ResourceManager.GetString("Example6_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   !!str &amp;a1 &quot;foo&quot;:
        ///  !!str bar
        ///&amp;a2 baz : *a1
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_23 {
            get {
                return ResourceManager.GetString("Example6_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   !&lt;tag:yaml.org,2002:str&gt; foo :
        ///  !&lt;!bar&gt; baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_24 {
            get {
                return ResourceManager.GetString("Example6_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - !&lt;!&gt; foo
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_25a {
            get {
                return ResourceManager.GetString("Example6_25a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - !&lt;$:?&gt; bar
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_25b {
            get {
                return ResourceManager.GetString("Example6_25b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !e! tag:example.com,2000:app/
        ///---
        ///- !local foo
        ///- !!str bar
        ///- !e!tag%21 baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_26 {
            get {
                return ResourceManager.GetString("Example6_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !e! tag:example,2000:app/
        ///---
        ///- !e! foo
        ///- !h!bar baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_27a {
            get {
                return ResourceManager.GetString("Example6_27a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %TAG !e! tag:example,2000:app/
        ///---
        ///- !h!bar baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_27b {
            get {
                return ResourceManager.GetString("Example6_27b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Assuming conventional resolution:
        ///- &quot;12&quot;
        ///- 12
        ///- ! 12
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_28 {
            get {
                return ResourceManager.GetString("Example6_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First occurrence: &amp;anchor Value
        ///Second occurrence: *anchor
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_29 {
            get {
                return ResourceManager.GetString("Example6_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - foo:	 bar
        ///- - baz
        ///  -	baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_3 {
            get {
                return ResourceManager.GetString("Example6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   plain: text
        ///  lines
        ///quoted: &quot;text
        ///  	lines&quot;
        ///block: |
        ///  text
        ///   	lines
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_4 {
            get {
                return ResourceManager.GetString("Example6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folding:
        ///  &quot;Empty line
        ///   	
        ///  as a line feed&quot;
        ///Chomping: |
        ///  Clipped empty lines
        /// 
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_5 {
            get {
                return ResourceManager.GetString("Example6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;-
        ///  trimmed
        ///  
        /// 
        ///
        ///  as
        ///  space
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_6 {
            get {
                return ResourceManager.GetString("Example6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;
        ///  foo 
        /// 
        ///  	 bar
        ///
        ///  baz
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_7 {
            get {
                return ResourceManager.GetString("Example6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;
        ///  foo 
        /// 
        ///  	 bar
        ///
        ///  baz
        ///&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_8 {
            get {
                return ResourceManager.GetString("Example6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   key:    # Comment
        ///  value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example6_9 {
            get {
                return ResourceManager.GetString("Example6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First occurrence: &amp;anchor Foo
        ///Second occurrence: *anchor
        ///Override anchor: &amp;anchor Bar
        ///Reuse anchor: *anchor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_1 {
            get {
                return ResourceManager.GetString("Example7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Outside flow collection:
        ///- ::vector
        ///- &quot;: - ()&quot;
        ///- Up, up, and away!
        ///- -123
        ///- http://example.com/foo#bar
        ///# Inside flow collection:
        ///- [ ::vector,
        ///  &quot;: - ()&quot;,
        ///  &quot;Up, up, and away!&quot;,
        ///  -123,
        ///  http://example.com/foo#bar ]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_10 {
            get {
                return ResourceManager.GetString("Example7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   implicit key : {
        ///  also implicit : value,
        ///  ? not a
        ///  implicit key : another
        ///  value
        /// }
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_11 {
            get {
                return ResourceManager.GetString("Example7_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st non-empty,
        ///
        /// 2nd non-empty, 
        ///	3rd non-empty
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_12 {
            get {
                return ResourceManager.GetString("Example7_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - [ one, two, ]
        ///- [three ,four] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_13 {
            get {
                return ResourceManager.GetString("Example7_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///&quot;double
        /// quoted&quot;, &apos;single
        ///           quoted&apos;,
        ///plain
        /// text, [ nested ],
        ///single: pair,
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_14 {
            get {
                return ResourceManager.GetString("Example7_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - { one : two , three: four , }
        ///- {five: six,seven : eight} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_15 {
            get {
                return ResourceManager.GetString("Example7_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///? explicit: entry,
        ///implicit: entry,
        ///?
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_16 {
            get {
                return ResourceManager.GetString("Example7_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///unquoted : &quot;separate&quot;,
        ///http://foo.com,
        ///omitted:,
        ///: omitted,
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_17 {
            get {
                return ResourceManager.GetString("Example7_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///&quot;adjacent&quot;:value,
        ///&quot;readable&quot;: value,
        ///&quot;empty&quot;:
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_18 {
            get {
                return ResourceManager.GetString("Example7_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///foo: bar
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_19 {
            get {
                return ResourceManager.GetString("Example7_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  foo : !!str,
        ///  !!str : bar,
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_2 {
            get {
                return ResourceManager.GetString("Example7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///? foo
        /// bar : baz
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_20 {
            get {
                return ResourceManager.GetString("Example7_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - [ YAML : separate ]
        ///- [ : empty key entry ]
        ///- [ {JSON: like}:adjacent ]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_21 {
            get {
                return ResourceManager.GetString("Example7_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ foo
        /// bar: invalid ]
        ///  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_22a {
            get {
                return ResourceManager.GetString("Example7_22a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [&quot;foo...&gt;1K characters....aldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsapofiaporuelkvnkd;aliurpeaurj;odakjfaldskfjdsalfkjdsap [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_22b {
            get {
                return ResourceManager.GetString("Example7_22b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - [ a, b ]
        ///- { a: b }
        ///- &quot;a&quot;
        ///- &apos;b&apos;
        ///- c に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_23 {
            get {
                return ResourceManager.GetString("Example7_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - !!str &quot;a&quot;
        ///- &apos;b&apos;
        ///- &amp;anchor &quot;c&quot;
        ///- *anchor
        ///- a
        ///- !!str b
        ///- !!str に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_24 {
            get {
                return ResourceManager.GetString("Example7_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  ? foo :,
        ///  : bar,
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_3 {
            get {
                return ResourceManager.GetString("Example7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;implicit key&quot; : {
        ///  &quot;also implicit&quot; : value,
        ///  ? &quot;not a
        ///  implicit key&quot; : &quot;another
        ///  value&quot;
        /// }
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_4 {
            get {
                return ResourceManager.GetString("Example7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;folded 
        ///to a space,	
        /// 
        ///to a line feed, or 	\
        /// \ 	non-content&quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_5 {
            get {
                return ResourceManager.GetString("Example7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot; 1st non-empty,
        ///
        /// 2nd non-empty, 
        ///	3rd non-empty &quot;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_6 {
            get {
                return ResourceManager.GetString("Example7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;here&apos;&apos;s to &quot;quotes&quot;&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_7 {
            get {
                return ResourceManager.GetString("Example7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;implicit key&apos; : {
        ///  &apos;also implicit&apos; : value,
        ///  ? &apos;not a
        ///  implicit key&apos; : &apos;another
        ///  value&apos;
        /// }
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_8 {
            get {
                return ResourceManager.GetString("Example7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos; 1st non-empty,
        ///
        /// 2nd non-empty, 
        ///	3rd non-empty &apos;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example7_9 {
            get {
                return ResourceManager.GetString("Example7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - | # Empty header
        /// literal
        ///- &gt;1 # Indentation indicator
        ///  folded
        ///- |+ # Chomping indicator
        /// keep
        ///
        ///- &gt;1- # Both indicators
        ///  strip
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_1 {
            get {
                return ResourceManager.GetString("Example8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;
        ///
        /// folded
        /// line
        ///
        /// next
        /// line
        ///   * bullet
        ///
        ///   * list
        ///   * lines
        ///
        /// last
        /// line
        ///
        ///# Comment
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_10 {
            get {
                return ResourceManager.GetString("Example8_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   block sequence:
        ///  - one
        ///  - two : three
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_14 {
            get {
                return ResourceManager.GetString("Example8_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - # Empty
        ///- |
        /// block node
        ///- - one # Compact
        ///  - two # sequence
        ///- one: two # Compact mapping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_15 {
            get {
                return ResourceManager.GetString("Example8_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   block mapping:
        /// key: value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_16 {
            get {
                return ResourceManager.GetString("Example8_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ? explicit key # Empty value
        ///? |
        ///  block key
        ///: - one # Explicit compact
        ///  - two # block value
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_17 {
            get {
                return ResourceManager.GetString("Example8_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   plain key: in-line value
        ///: # Both empty
        ///&quot;quoted key&quot;:
        ///- entry
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_18 {
            get {
                return ResourceManager.GetString("Example8_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - sun: yellow
        ///- ? earth: blue
        ///  : moon: white
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_19 {
            get {
                return ResourceManager.GetString("Example8_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - |
        /// detected
        ///- &gt;
        /// 
        ///  
        ///  # detected
        ///- |1
        ///  explicit
        ///- &gt;
        /// 	
        /// detected
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_2 {
            get {
                return ResourceManager.GetString("Example8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -
        ///  &quot;flow in block&quot;
        ///- &gt;
        /// Block scalar
        ///- !!map # Block collection
        ///  foo : bar
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_20 {
            get {
                return ResourceManager.GetString("Example8_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   literal: |2
        ///  value
        ///folded:
        ///   !foo
        ///  &gt;1
        /// value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_21 {
            get {
                return ResourceManager.GetString("Example8_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sequence: !!seq
        ///- entry
        ///- !!seq
        /// - nested
        ///mapping: !!map
        /// foo: bar
        ///  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_22 {
            get {
                return ResourceManager.GetString("Example8_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - |
        ///  
        /// text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_3a {
            get {
                return ResourceManager.GetString("Example8_3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - &gt;
        ///  text
        /// text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_3b {
            get {
                return ResourceManager.GetString("Example8_3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - |2
        /// text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_3c {
            get {
                return ResourceManager.GetString("Example8_3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   strip: |-
        ///  text
        ///clip: |
        ///  text
        ///keep: |+
        ///  text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_4 {
            get {
                return ResourceManager.GetString("Example8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    # Strip
        ///  # Comments:
        ///strip: |-
        ///  # text
        ///  
        /// # Clip
        ///  # comments:
        ///
        ///clip: |
        ///  # text
        /// 
        /// # Keep
        ///  # comments:
        ///
        ///keep: |+
        ///  # text
        ///
        /// # Trail
        ///  # comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_5 {
            get {
                return ResourceManager.GetString("Example8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   strip: &gt;-
        ///
        ///clip: &gt;
        ///
        ///keep: |+
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_6 {
            get {
                return ResourceManager.GetString("Example8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |
        /// literal
        /// 	text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_7 {
            get {
                return ResourceManager.GetString("Example8_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |
        /// 
        ///  
        ///  literal
        ///   
        ///  
        ///  text
        ///
        /// # Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_8 {
            get {
                return ResourceManager.GetString("Example8_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;
        /// folded
        /// text
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example8_9 {
            get {
                return ResourceManager.GetString("Example8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # Comment
        ///# lines
        ///Document
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_1 {
            get {
                return ResourceManager.GetString("Example9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %YAML 1.2
        ///---
        ///Document
        ///... # Suffix
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_2 {
            get {
                return ResourceManager.GetString("Example9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bare
        ///document
        ///...
        ///# No document
        ///...
        ///|
        ///%!PS-Adobe-2.0 # Not the first line
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_3 {
            get {
                return ResourceManager.GetString("Example9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ---
        ///{ matches
        ///% : 20 }
        ///...
        ///---
        ///# Empty
        ///...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_4 {
            get {
                return ResourceManager.GetString("Example9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %YAML 1.2
        ///--- |
        ///%!PS-Adobe-2.0
        ///...
        ///%YAML1.2
        ///---
        ///# Empty
        ///...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_5 {
            get {
                return ResourceManager.GetString("Example9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document
        ///---
        ///# Empty
        ///...
        ///%YAML 1.2
        ///---
        ///matches %: 20
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Example9_6 {
            get {
                return ResourceManager.GetString("Example9_6", resourceCulture);
            }
        }
    }
}
